import { JobPosting, Candidate, User } from './types';

export const MOCK_USER: User = {
    name: "HR Manager",
    email: "manager@recruitflow.app",
    avatar: "https://picsum.photos/seed/user/40/40",
};

export const MOCK_JOBS: JobPosting[] = [
  {
    id: "JOB-001",
    title: "Senior Frontend Developer",
    description: "We are looking for a Senior Frontend Developer to join our team.",
    skills: ["React", "TypeScript", "Next.js"],
    department: "Engineering",
    location: "Ho Chi Minh City",
    salary: "$2,000 - $3,500",
    status: "Open",
    applications: 25,
    postedDate: "2024-07-15T13:00:00Z",
    deadline: "2024-08-30",
  },
  {
    id: "JOB-002",
    title: "Product Manager",
    description: "We are looking for a Product Manager to join our team.",
    skills: ["Agile", "Scrum", "JIRA"],
    department: "Product",
    location: "Remote",
    salary: "$2,500 - $4,000",
    status: "Open",
    applications: 42,
    postedDate: "2024-07-10T13:00:00Z",
    deadline: "2024-08-25",
  },
  {
    id: "JOB-003",
    title: "UI/UX Designer",
    description: "We are looking for a UI/UX Designer to join our team.",
    skills: ["Figma", "Sketch", "Adobe XD"],
    department: "Design",
    location: "Hanoi",
    salary: "$1,500 - $2,500",
    status: "On hold",
    applications: 15,
    postedDate: "2024-07-05T13:00:00Z",
    deadline: "2024-09-10",
  },
  {
    id: "JOB-004",
    title: "DevOps Engineer",
    description: "We are looking for a DevOps Engineer to join our team.",
    skills: ["AWS", "Docker", "Kubernetes"],
    department: "Engineering",
    location: "Da Nang",
    salary: "$2,200 - $3,800",
    status: "Closed",
    applications: 31,
    postedDate: "2024-06-20T13:00:00Z",
    deadline: "2024-07-20",
  },
];

export const MOCK_CANDIDATES: Candidate[] = [
  {
    id: "CAND-001",
    name: "Alice Wonderland",
    email: "alice@example.com",
    avatar: "https://picsum.photos/seed/avatar1/40/40",
    jobId: "JOB-001",
    jobTitle: "Senior Frontend Developer",
    stage: "Interview",
    skills: ["React", "TypeScript", "Next.js", "GraphQL"],
    lastContact: "2024-07-28",
  },
  {
    id: "CAND-002",
    name: "Bob Builder",
    email: "bob@example.com",
    avatar: "https://picsum.photos/seed/avatar2/40/40",
    jobId: "JOB-001",
    jobTitle: "Senior Frontend Developer",
    stage: "Applied",
    skills: ["Vue.js", "JavaScript", "CSS", "HTML"],
    lastContact: "2024-07-29",
  },
  {
    id: "CAND-003",
    name: "Charlie Chaplin",
    email: "charlie@example.com",
    avatar: "https://picsum.photos/seed/avatar3/40/40",
    jobId: "JOB-002",
    jobTitle: "Product Manager",
    stage: "Screening",
    skills: ["Agile", "Scrum", "JIRA", "Roadmap"],
    lastContact: "2024-07-25",
  },
    {
    id: "CAND-004",
    name: "Diana Prince",
    email: "diana@example.com",
    avatar: "https://picsum.photos/seed/avatar4/40/40",
    jobId: "JOB-003",
    jobTitle: "UI/UX Designer",
    stage: "Offered",
    skills: ["Figma", "Sketch", "Adobe XD", "Prototyping"],
    lastContact: "2024-07-22",
  },
  {
    id: "CAND-005",
    name: "Ethan Hunt",
    email: "ethan@example.com",
    avatar: "https://picsum.photos/seed/avatar5/40/40",
    jobId: "JOB-002",
    jobTitle: "Product Manager",
    stage: "Hired",
    skills: ["Market Research", "User Stories", "Go-to-market"],
    lastContact: "2024-07-15",
  },
  {
    id: "CAND-006",
    name: "Fiona Glenanne",
    email: "fiona@example.com",
    avatar: "https://picsum.photos/seed/avatar6/40/40",
    jobId: "JOB-004",
    jobTitle: "DevOps Engineer",
    stage: "Rejected",
    skills: ["AWS", "Docker", "Kubernetes", "CI/CD"],
    lastContact: "2024-07-18",
  },
    {
    id: "CAND-007",
    name: "George Costanza",
    email: "george@example.com",
    avatar: "https://picsum.photos/seed/avatar7/40/40",
    jobId: "JOB-001",
    jobTitle: "Senior Frontend Developer",
    stage: "Applied",
    skills: ["Angular", "TypeScript", "RxJS"],
    lastContact: "2024-07-30",
  },
  {
    id: "CAND-008",
    name: "Hannah Montana",
    email: "hannah@example.com",
    avatar: "https://picsum.photos/seed/avatar8/40/40",
    jobId: "JOB-002",
    jobTitle: "Product Manager",
    stage: "Interview",
    skills: ["Product Strategy", "A/B Testing", "Analytics"],
    lastContact: "2024-07-29",
  }
];
